version: '3.8'
services:
  couchdb:
    ports:
      - "5984:5984"
    image: couchdb:latest
    volumes:
      - couchdb:/opt/couchdb/data
      - type: bind
        source: ./couchdb/config.ini
        target: /opt/couchdb/etc/local.d/config.ini
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
volumes:
  couchdb:
